# Generated by Django 5.1.7 on 2025-03-12 13:49

import django.db.models.deletion
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=50, verbose_name='نام عملیات ')),
            ],
        ),
        migrations.CreateModel(
            name='OperationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_capacity', models.CharField(blank=True, choices=[('gal', 'گالن'), ('but', 'بوته'), ('kilo', 'کیلو گرم')], max_length=10, null=True, verbose_name='واحد محاسبه ')),
                ('capacity', models.IntegerField(default=0, verbose_name='تعداد کوره برای انجام این عملیات ')),
                ('capacity_materials', models.IntegerField(default=1, verbose_name='حجم مواد')),
                ('zamini', models.BooleanField(default=False, verbose_name='ذوب زمینی دارد؟')),
                ('Product', models.CharField(blank=True, max_length=20, null=True, verbose_name='نام محصول')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.operation', verbose_name='نوع عملیات')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='نام کاربری')),
                ('phone_number', models.CharField(max_length=15, verbose_name='تلفن همراه')),
                ('status_date', models.DateField(blank=True, default=jdatetime.date.today, null=True, verbose_name='تاریخ ')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='حجم مواد')),
                ('unit', models.CharField(blank=True, choices=[('gal', 'گالن'), ('but', 'بوته'), ('kilo', 'کیلو گرم')], max_length=15, null=True, verbose_name='واحد محاسبه')),
                ('start_session', models.TimeField(blank=True, default='08:00', max_length=20, null=True, verbose_name='از ساعت ')),
                ('end_session', models.TimeField(blank=True, default='12:00', max_length=20, null=True, verbose_name='تا ساعت ')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.operation', verbose_name='نوع عملیات')),
            ],
        ),
    ]
