# Generated by Django 5.1.7 on 2025-04-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='status_date',
            new_name='shamsi_date',
        ),
    ]
