# Generated by Django 5.1.7 on 2025-03-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='تلفن همراه')),
            ],
        ),
        migrations.AlterField(
            model_name='time',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='تلفن همراه'),
        ),
    ]
