# Generated by Django 5.1.7 on 2025-03-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_is_verified_user_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
    ]
